# Generated by Django 4.2.5 on 2023-09-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contacts_alter_blog_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
